app_data:
    resource: "@AppDataBundle/Resources/config/routing.yml"
    prefix:   /app_data

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api_host:
    path:   /api

logout:
    path:   /logout