# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:


    encoders:
        AppDataBundle\Entity\Users:
            algorithm: bcrypt
            cost: 12


    providers:
        in_memory:
            memory: ~
        our_db_provider:
            entity:
                class: AppDataBundle\Entity\Users
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
                pattern:   ^/login$
                anonymous: ~

        mails:
            pattern:   ^/flush_mails/.*
            security:  false

        main:
            pattern:    ^/(?!/flush_mails/)
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login_check

            logout:
                path:   /logout
                invalidate_session: false
                target: /

    # http_basic: ~
    # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

    # form_login: ~
    # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
